trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
    displayName: 'Set up Python'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pytest
    displayName: 'Run unit tests'

  - task: Docker@2
    displayName: 'Build and push Docker image'
    inputs:
      containerRegistry: 'dockerhub-connection'
      repository: 'yelenaker/lab1-cicd'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        latest